server:
  port: 9001
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: gateway_01
          uri: http://localhost:8881
          predicates:
            - Path=/system/test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
